config/routes.rb
Kwejk::Application.routes.draw do

  resources :mems do
    collection do
      get 'my'
      get 'inactive'
    end
  end
  root :to => 'mems#index'

  get "home/index"
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mem.rb
class Mem < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
  :default_url => "/images/:style/missing.png"
  validates_attachment_presence :image
  validates :name,presence: :true
  validates :description,presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :mems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mems_controller.rb
class MemsController < ApplicationController
  before_action :set_mem, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! , only: [:new,:show,:edit,:update,:my]

  # GET /mems
  # GET /mems.json
  def index
    @mems = Mem.where(active: true)
  end

  def inactive
    @mems = Mem.where(active: false)
    render :index
  end


  # GET /mems/1
  # GET /mems/1.json
  def show
  end

  # GET /mems/new
  def new
    @mem = Mem.new
  end

  def my
    @mems = current_user.mems
    render :index
  end


  # GET /mems/1/edit
  def edit
  end

  # POST /mems
  # POST /mems.json
  def create
    @mem = current_user.mems.new(mem_params)
    @mem.image = params[:mem][:image]
    @mem.active = false
    respond_to do |format|
      if @mem.save
        format.html { redirect_to @mem, notice: 'Mem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mem }
      else
        format.html { render action: 'new' }
        format.json { render json: @mem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mems/1
  # PATCH/PUT /mems/1.json
  def update
    respond_to do |format|
      if @mem.update(mem_params)
        format.html { redirect_to @mem, notice: 'Mem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mems/1
  # DELETE /mems/1.json
  def destroy
    @mem.destroy
    respond_to do |format|
      format.html { redirect_to mems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mem
      @mem = Mem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mem_params
      params.require(:mem).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mems_helper.rb
module MemsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kwejk" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

  <div class="navbar navbar-fluid-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Kwejk</a>
        <div class="container-fluid nav-collapse">
          <ul class="nav">
            <li><%= link_to "Waiting room", inactive_mems_path %></li>
            <li><%= link_to "Mems", my_mems_path %></li>
            <li><%= link_to "My mems", my_mems_path %></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span3">
        <div class="well sidebar-nav">
          <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>
            <% if user_signed_in? %>
                <li><%= link_to "Edit user", edit_user_registration_path %></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
            <% else %>
                <li>
                  <%= link_to('Login', new_user_session_path) %>
                </li>
            <% end %>
          </ul>
        </div>
        <!--/.well -->
      </div>
      <!--/span-->
      <div class="span9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>


      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/mems/_form.html.erb
<%= form_for @mem, :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'text_field' %>
      </div>
      <div class="controls">
        <%= f.file_field :image, :class => 'file_field' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  mems_path, :class => 'btn' %>
    </div>
<% end %>

app/views/mems/edit.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mems/index.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:image) %></th>
  </tr>
  </thead>
  <tbody>
  <% @mems.each do |mem| %>
      <tr>
        <td><%= mem.name %></td>
        <td><%= mem.description %></td>
        <td><%= image_tag mem.image.url %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mem_path,
            :class => 'btn btn-primary' %>

app/views/mems/new.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mems/show.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @mem.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @mem.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= image_tag @mem.image.url %></dd>
</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              mems_path, :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mem_path(@mem), :class => 'btn' %>
</div>